version: '3'
services:
  metric-broadcaster:
    image: metric-broadcaster
    networks:
      - metrics-network
    ports:
      - 4000:4000
    depends_on:
      - metric-generator
    restart: unless-stopped

  metric-generator:
    image: metric-generator
    networks:
      - metrics-network
    ports:
      - 8080:8080

  frontend:
    image: frontend
    networks:
      - metrics-network
    ports:
      - 3000:3000
    depends_on:
      - metric-broadcaster

  reverse-proxy:
    image: reverse-proxy
    networks:
      - metrics-network
    ports:
      - 80:80
    depends_on:
      - frontend
    restart: unless-stopped

networks:
  metrics-network:
    driver: bridge